# ----
# Site

title: Yash Farms to Table
url: "https://yashfarmtotable.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
snipcart_key: "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Local Pune based vegetable delivery service.
author:
  name: shilpa mehta
  phone: "+917083983908"
social:
  name: Yash Farms To Table
  links:
    - https://github.com/CloudCannon/fur-jekyll-template
# -----
# Build
timezone: Etc/UTC

collections_dir: _products
collections:
  products:
    _hide_content: true
    output: true
  vegetables:
    _hide_content: true
    output: true
  fruits:
    _hide_content: true
    output: true
  spices:
    _hide_content: true
    output: true
  flowers:
    _hide_content: true
    output: true


permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "vegetables"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "fruits"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "flowers"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "spices"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
